import os
from datetime import datetime
import requests
import zipfile
import logging

import pandas as pd
import duckdb
import pyarrow.csv as pv
import pyarrow.parquet as pq

from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
from airflow.providers.google.cloud.hooks.gcs import GCSHook

# Global configuration values
PROJECT_ID = "dtc-de-course-447715"
BUCKET = "cms_bucket_jj"
BIGQUERY_DATASET = "CMS"
path_to_local_home = os.environ.get("AIRFLOW_HOME", "/opt/airflow")
EXTRACT_PATH = os.path.join(path_to_local_home, "downloaded_files")
FILE_TYPES = ["RSRCH", "OWNRSHP", "GNRL"]

# URL template for the file to download (templated with execution_date)
url_template = "https://download.cms.gov/openpayments/PGYR{{ execution_date.strftime('%Y') }}_P01302025_01212025.zip"

def download_and_unzip(url, extract_path, **kwargs):
    """
    Download a zip file from the rendered URL and extract its contents.
    """
    execution_date = kwargs.get('execution_date')
    formatted_url = (
        url.replace("{{ execution_date.strftime('%Y') }}", execution_date.strftime('%Y'))
        if execution_date else url
    )

    os.makedirs(extract_path, exist_ok=True)
    logging.info(f"Downloading file from {formatted_url}...")

    # Download the zip file and check for errors
    response = requests.get(formatted_url)
    response.raise_for_status()

    zip_path = os.path.join(extract_path, 'downloaded_file.zip')
    with open(zip_path, 'wb') as f:
        f.write(response.content)

    logging.info("Extracting files...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)

    os.remove(zip_path)
    logging.info("Download and extraction complete.")
    return extract_path

def list_files(extract_path, **kwargs):
    """
    List all CSV files found in the extraction directory.
    """
    csv_files = [f for f in os.listdir(extract_path) if f.endswith('.csv')]
    logging.info("Found CSV files: %s", csv_files)
    return csv_files

def convert_dtl_rsrch_to_parquet(extract_path, **kwargs):
    """
    Convert CSV files with 'DTL_RSRCH' in the filename to Parquet.
    """
    execution_date = kwargs.get('execution_date')
    year = execution_date.strftime('%Y')
    found_file = False
    
    for file in os.listdir(extract_path):
        if 'DTL_RSRCH' in file and file.endswith('.csv'):
            input_csv = os.path.join(extract_path, file)
            output_parquet = os.path.join(extract_path, f"RSRCH_{year}.parquet")
            print(f"Converting {input_csv} to Parquet...")
            dtype_dict_rsrch = {
        "Change_Type": str,
        "Covered_Recipient_Type": str,
        "Noncovered_Recipient_Entity_Name": str,
        "Teaching_Hospital_CCN": str,
        "Teaching_Hospital_ID": str,
        "Teaching_Hospital_Name": str,
        "Covered_Recipient_Profile_ID": str,
        "Covered_Recipient_NPI": str,
        "Covered_Recipient_First_Name": str,
        "Covered_Recipient_Middle_Name": str,
        "Covered_Recipient_Last_Name": str,
        "Covered_Recipient_Name_Suffix": str,
        "Recipient_Primary_Business_Street_Address_Line1": str,
        "Recipient_Primary_Business_Street_Address_Line2": str,
        "Recipient_City": str,
        "Recipient_State": str,
        "Recipient_Zip_Code": str,
        "Recipient_Country": str,
        "Recipient_Province": str,
        "Recipient_Postal_Code": str,
        "Covered_Recipient_Primary_Type_1": str,
        "Covered_Recipient_Primary_Type_2": str,
        "Covered_Recipient_Primary_Type_3": str,
        "Covered_Recipient_Primary_Type_4": str,
        "Covered_Recipient_Primary_Type_5": str,
        "Covered_Recipient_Primary_Type_6": str,
        "Covered_Recipient_Specialty_1": str,
        "Covered_Recipient_Specialty_2": str,
        "Covered_Recipient_Specialty_3": str,
        "Covered_Recipient_Specialty_4": str,
        "Covered_Recipient_Specialty_5": str,
        "Covered_Recipient_Specialty_6": str,
        "Covered_Recipient_License_State_code1": str,
        "Covered_Recipient_License_State_code2": str,
        "Covered_Recipient_License_State_code3": str,
        "Covered_Recipient_License_State_code4": str,
        "Covered_Recipient_License_State_code5": str,
        "Principal_Investigator_1_Covered_Recipient_Type": str,
        "Principal_Investigator_1_Profile_ID": str,
        "Principal_Investigator_1_NPI": str,
        "Principal_Investigator_1_First_Name": str,
        "Principal_Investigator_1_Middle_Name": str,
        "Principal_Investigator_1_Last_Name": str,
        "Principal_Investigator_1_Name_Suffix": str,
        "Principal_Investigator_1_Business_Street_Address_Line1": str,
        "Principal_Investigator_1_Business_Street_Address_Line2": str,
        "Principal_Investigator_1_City": str,
        "Principal_Investigator_1_State": str,
        "Principal_Investigator_1_Zip_Code": str,
        "Principal_Investigator_1_Country": str,
        "Principal_Investigator_1_Province": str,
        "Principal_Investigator_1_Postal_Code": str,
        "Principal_Investigator_1_Primary_Type_1": str,
        "Principal_Investigator_1_Primary_Type_2": str,
        "Principal_Investigator_1_Primary_Type_3": str,
        "Principal_Investigator_1_Primary_Type_4": str,
        "Principal_Investigator_1_Primary_Type_5": str,
        "Principal_Investigator_1_Primary_Type_6": str,
        "Principal_Investigator_1_Specialty_1": str,
        "Principal_Investigator_1_Specialty_2": str,
        "Principal_Investigator_1_Specialty_3": str,
        "Principal_Investigator_1_Specialty_4": str,
        "Principal_Investigator_1_Specialty_5": str,
        "Principal_Investigator_1_Specialty_6": str,
        "Principal_Investigator_1_License_State_code1": str,
        "Principal_Investigator_1_License_State_code2": str,
        "Principal_Investigator_1_License_State_code3": str,
        "Principal_Investigator_1_License_State_code4": str,
        "Principal_Investigator_1_License_State_code5": str,
        "Principal_Investigator_2_Covered_Recipient_Type": str,
        "Principal_Investigator_2_Profile_ID": str,
        "Principal_Investigator_2_NPI": str,
        "Principal_Investigator_2_First_Name": str,
        "Principal_Investigator_2_Middle_Name": str,
        "Principal_Investigator_2_Last_Name": str,
        "Principal_Investigator_2_Name_Suffix": str,
        "Principal_Investigator_2_Business_Street_Address_Line1": str,
        "Principal_Investigator_2_Business_Street_Address_Line2": str,
        "Principal_Investigator_2_City": str,
        "Principal_Investigator_2_State": str,
        "Principal_Investigator_2_Zip_Code": str,
        "Principal_Investigator_2_Country": str,
        "Principal_Investigator_2_Province": str,
        "Principal_Investigator_2_Postal_Code": str,
        "Principal_Investigator_2_Primary_Type_1": str,
        "Principal_Investigator_2_Primary_Type_2": str,
        "Principal_Investigator_2_Primary_Type_3": str,
        "Principal_Investigator_2_Primary_Type_4": str,
        "Principal_Investigator_2_Primary_Type_5": str,
        "Principal_Investigator_2_Primary_Type_6": str,
        "Principal_Investigator_2_Specialty_1": str,
        "Principal_Investigator_2_Specialty_2": str,
        "Principal_Investigator_2_Specialty_3": str,
        "Principal_Investigator_2_Specialty_4": str,
        "Principal_Investigator_2_Specialty_5": str,
        "Principal_Investigator_2_Specialty_6": str,
        "Principal_Investigator_2_License_State_code1": str,
        "Principal_Investigator_2_License_State_code2": str,
        "Principal_Investigator_2_License_State_code3": str,
        "Principal_Investigator_2_License_State_code4": str,
        "Principal_Investigator_2_License_State_code5": str,
        "Principal_Investigator_3_Covered_Recipient_Type": str,
        "Principal_Investigator_3_Profile_ID": str,
        "Principal_Investigator_3_NPI": str,
        "Principal_Investigator_3_First_Name": str,
        "Principal_Investigator_3_Middle_Name": str,
        "Principal_Investigator_3_Last_Name": str,
        "Principal_Investigator_3_Name_Suffix": str,
        "Principal_Investigator_3_Business_Street_Address_Line1": str,
        "Principal_Investigator_3_Business_Street_Address_Line2": str,
        "Principal_Investigator_3_City": str,
        "Principal_Investigator_3_State": str,
        "Principal_Investigator_3_Zip_Code": str,
        "Principal_Investigator_3_Country": str,
        "Principal_Investigator_3_Province": str,
        "Principal_Investigator_3_Postal_Code": str,
        "Principal_Investigator_3_Primary_Type_1": str,
        "Principal_Investigator_3_Primary_Type_2": str,
        "Principal_Investigator_3_Primary_Type_3": str,
        "Principal_Investigator_3_Primary_Type_4": str,
        "Principal_Investigator_3_Primary_Type_5": str,
        "Principal_Investigator_3_Primary_Type_6": str,
        "Principal_Investigator_3_Specialty_1": str,
        "Principal_Investigator_3_Specialty_2": str,
        "Principal_Investigator_3_Specialty_3": str,
        "Principal_Investigator_3_Specialty_4": str,
        "Principal_Investigator_3_Specialty_5": str,
        "Principal_Investigator_3_Specialty_6": str,
        "Principal_Investigator_3_License_State_code1": str,
        "Principal_Investigator_3_License_State_code2": str,
        "Principal_Investigator_3_License_State_code3": str,
        "Principal_Investigator_3_License_State_code4": str,
        "Principal_Investigator_3_License_State_code5": str,
        "Principal_Investigator_4_Covered_Recipient_Type": str,
        "Principal_Investigator_4_Profile_ID": str,
        "Principal_Investigator_4_NPI": str,
        "Principal_Investigator_4_First_Name": str,
        "Principal_Investigator_4_Middle_Name": str,
        "Principal_Investigator_4_Last_Name": str,
        "Principal_Investigator_4_Name_Suffix": str,
        "Principal_Investigator_4_Business_Street_Address_Line1": str,
        "Principal_Investigator_4_Business_Street_Address_Line2": str,
        "Principal_Investigator_4_City": str,
        "Principal_Investigator_4_State": str,
        "Principal_Investigator_4_Zip_Code": str,
        "Principal_Investigator_4_Country": str,
        "Principal_Investigator_4_Province": str,
        "Principal_Investigator_4_Postal_Code": str,
        "Principal_Investigator_4_Primary_Type_1": str,
        "Principal_Investigator_4_Primary_Type_2": str,
        "Principal_Investigator_4_Primary_Type_3": str,
        "Principal_Investigator_4_Primary_Type_4": str,
        "Principal_Investigator_4_Primary_Type_5": str,
        "Principal_Investigator_4_Primary_Type_6": str,
        "Principal_Investigator_4_Specialty_1": str,
        "Principal_Investigator_4_Specialty_2": str,
        "Principal_Investigator_4_Specialty_3": str,
        "Principal_Investigator_4_Specialty_4": str,
        "Principal_Investigator_4_Specialty_5": str,
        "Principal_Investigator_4_Specialty_6": str,
        "Principal_Investigator_4_License_State_code1": str,
        "Principal_Investigator_4_License_State_code2": str,
        "Principal_Investigator_4_License_State_code3": str,
        "Principal_Investigator_4_License_State_code4": str,
        "Principal_Investigator_4_License_State_code5": str,
        "Principal_Investigator_5_Covered_Recipient_Type": str,
        "Principal_Investigator_5_Profile_ID": str,
        "Principal_Investigator_5_NPI": str,
        "Principal_Investigator_5_First_Name": str,
        "Principal_Investigator_5_Middle_Name": str,
        "Principal_Investigator_5_Last_Name": str,
        "Principal_Investigator_5_Name_Suffix": str,
        "Principal_Investigator_5_Business_Street_Address_Line1": str,
        "Principal_Investigator_5_Business_Street_Address_Line2": str,
        "Principal_Investigator_5_City": str,
        "Principal_Investigator_5_State": str,
        "Principal_Investigator_5_Zip_Code": str,
        "Principal_Investigator_5_Country": str,
        "Principal_Investigator_5_Province": str,
        "Principal_Investigator_5_Postal_Code": str,
        "Principal_Investigator_5_Primary_Type_1": str,
        "Principal_Investigator_5_Primary_Type_2": str,
        "Principal_Investigator_5_Primary_Type_3": str,
        "Principal_Investigator_5_Primary_Type_4": str,
        "Principal_Investigator_5_Primary_Type_5": str,
        "Principal_Investigator_5_Primary_Type_6": str,
        "Principal_Investigator_5_Specialty_1": str,
        "Principal_Investigator_5_Specialty_2": str,
        "Principal_Investigator_5_Specialty_3": str,
        "Principal_Investigator_5_Specialty_4": str,
        "Principal_Investigator_5_Specialty_5": str,
        "Principal_Investigator_5_Specialty_6": str,
        "Principal_Investigator_5_License_State_code1": str,
        "Principal_Investigator_5_License_State_code2": str,
        "Principal_Investigator_5_License_State_code3": str,
        "Principal_Investigator_5_License_State_code4": str,
        "Principal_Investigator_5_License_State_code5": str,
        "Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name": str,
        "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID": int,
        "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name": str,
        "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State": str,
        "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country": str,
        "Related_Product_Indicator": str,
        "Covered_or_Noncovered_Indicator_1": str,
        "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1": str,
        "Product_Category_or_Therapeutic_Area_1": str,
        "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1": str,
        "Associated_Drug_or_Biological_NDC_1": str,
        "Associated_Device_or_Medical_Supply_PDI_1": str,
        "Covered_or_Noncovered_Indicator_2": str,
        "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2": str,
        "Product_Category_or_Therapeutic_Area_2": str,
        "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2": str,
        "Associated_Drug_or_Biological_NDC_2": str,
        "Associated_Device_or_Medical_Supply_PDI_2": str,
        "Covered_or_Noncovered_Indicator_3": str,
        "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3": str,
        "Product_Category_or_Therapeutic_Area_3": str,
        "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3": str,
        "Associated_Drug_or_Biological_NDC_3": str,
        "Associated_Device_or_Medical_Supply_PDI_3": str,
        "Covered_or_Noncovered_Indicator_4": str,
        "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4": str,
        "Product_Category_or_Therapeutic_Area_4": str,
        "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4": str,
        "Associated_Drug_or_Biological_NDC_4": str,
        "Associated_Device_or_Medical_Supply_PDI_4": str,
        "Covered_or_Noncovered_Indicator_5": str,
        "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5": str,
        "Product_Category_or_Therapeutic_Area_5": str,
        "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5": str,
        "Associated_Drug_or_Biological_NDC_5": str,
        "Associated_Device_or_Medical_Supply_PDI_5": str,
        "Total_Amount_of_Payment_USDollars": float,
        "Date_of_Payment": str,
        "Form_of_Payment_or_Transfer_of_Value": str,
        "Expenditure_Category1": str,
        "Expenditure_Category2": str,
        "Expenditure_Category3": str,
        "Expenditure_Category4": str,
        "Expenditure_Category5": str,
        "Expenditure_Category6": str,
        "Preclinical_Research_Indicator": str,
        "Delay_in_Publication_Indicator": str,
        "Name_of_Study": str,
        "Dispute_Status_for_Publication": str,
        "Record_ID": int,
        "Program_Year": int,
        "Payment_Publication_Date": str,
        "ClinicalTrials_Gov_Identifier": str,
        "Research_Information_Link": str,
        "Context_of_Research": str
            }
            df = pd.read_csv(input_csv, dtype=dtype_dict_rsrch)
            df.to_parquet(output_parquet, index=False)
            print(f"Converted {input_csv} to {output_parquet}")
            found_file = True

def upload_to_gcs_for_file(bucket, extract_path, **kwargs):
    """
    Upload the Parquet file for a given file_type to GCS.
    """
    execution_date = kwargs.get('execution_date')
    # Ensure execution_date is a datetime object.
    if not hasattr(execution_date, 'strftime'):
        execution_date = datetime.fromisoformat(execution_date)

    year = execution_date.strftime('%Y')
    file_name = f"RSRCH_{year}.parquet"
    local_file = os.path.join(extract_path, file_name)

    # Logging for debugging purposes
    logging.info("Looking for file: %s", local_file)
    logging.info("File exists: %s", os.path.exists(local_file))

    if not os.path.exists(local_file):
        logging.error("File %s does not exist. Directory contents: %s", local_file, os.listdir(extract_path))
        raise Exception(f"{local_file} does not exist")

    object_name = f"raw/{file_name}"
    logging.info("Uploading %s to gs://%s/%s...", local_file, bucket, object_name)
    hook = GCSHook(gcp_conn_id="gcp-airflow")
    hook.upload(
        bucket_name=bucket,
        object_name=object_name,
        filename=local_file,
        timeout=6000
    )
    logging.info("Uploaded %s to gs://%s/%s", local_file, bucket, object_name)
    return file_name

default_args = {
    "start_date": datetime(2018, 1, 1),
    "end_date": datetime(2023, 12, 31),
    "retries": 10,
}

with DAG(
    "GCP_ingestion_CMS_RSRCH",
    schedule_interval="0 0 1 1 *",
    default_args=default_args,
    catchup=True,
    max_active_runs=1,
    template_searchpath=[path_to_local_home],
) as dag:

    download_task = PythonOperator(
        task_id="download_and_unzip",
        python_callable=download_and_unzip,
        op_kwargs={'url': url_template, 'extract_path': EXTRACT_PATH},
    )

    list_task = PythonOperator(
        task_id="list_files",
        python_callable=list_files,
        op_kwargs={'extract_path': EXTRACT_PATH},
    )

    rsrch_to_parquet_task = PythonOperator(
        task_id="convert_dtl_rsrch_to_parquet",
        python_callable=convert_dtl_rsrch_to_parquet,
        op_kwargs={'extract_path': EXTRACT_PATH},
    )

    # Parquet file and table name templates (Jinja templated)
    parquet_filename_template = 'RSRCH_{{ execution_date.strftime(\'%Y\') }}.parquet'
    table_name_template = 'RSRCH_{{ execution_date.strftime(\'%Y\') }}'
    final_name_template = 'RSRCH_ALL'

    upload_to_gcs = PythonOperator(
        task_id="upload_to_gcs",
        python_callable=upload_to_gcs_for_file,
        op_kwargs={
            'bucket': BUCKET,
            'extract_path': EXTRACT_PATH
        },
        retries=10,
    )

    create_final_table_task = BigQueryInsertJobOperator(
        task_id="create_final_table",
        gcp_conn_id="gcp-airflow",
        configuration={
            "query": {
                "query": f"""
                    CREATE TABLE IF NOT EXISTS `{PROJECT_ID}.{BIGQUERY_DATASET}.{final_name_template}` (
                    filename STRING,
                    Change_Type STRING,
                    Covered_Recipient_Type STRING,
                    Noncovered_Recipient_Entity_Name STRING,
                    Teaching_Hospital_CCN STRING,
                    Teaching_Hospital_ID STRING,
                    Teaching_Hospital_Name STRING,
                    Covered_Recipient_Profile_ID STRING,
                    Covered_Recipient_NPI STRING,
                    Covered_Recipient_First_Name STRING,
                    Covered_Recipient_Middle_Name STRING,
                    Covered_Recipient_Last_Name STRING,
                    Covered_Recipient_Name_Suffix STRING,
                    Recipient_Primary_Business_Street_Address_Line1 STRING,
                    Recipient_Primary_Business_Street_Address_Line2 STRING,
                    Recipient_City STRING,
                    Recipient_State STRING,
                    Recipient_Zip_Code STRING,
                    Recipient_Country STRING,
                    Recipient_Province STRING,
                    Recipient_Postal_Code STRING,
                    Covered_Recipient_Primary_Type_1 STRING,
                    Covered_Recipient_Primary_Type_2 STRING,
                    Covered_Recipient_Primary_Type_3 STRING,
                    Covered_Recipient_Primary_Type_4 STRING,
                    Covered_Recipient_Primary_Type_5 STRING,
                    Covered_Recipient_Primary_Type_6 STRING,
                    Covered_Recipient_Specialty_1 STRING,
                    Covered_Recipient_Specialty_2 STRING,
                    Covered_Recipient_Specialty_3 STRING,
                    Covered_Recipient_Specialty_4 STRING,
                    Covered_Recipient_Specialty_5 STRING,
                    Covered_Recipient_Specialty_6 STRING,
                    Covered_Recipient_License_State_code1 STRING,
                    Covered_Recipient_License_State_code2 STRING,
                    Covered_Recipient_License_State_code3 STRING,
                    Covered_Recipient_License_State_code4 STRING,
                    Covered_Recipient_License_State_code5 STRING,
                    Principal_Investigator_1_Covered_Recipient_Type STRING,
                    Principal_Investigator_1_Profile_ID STRING,
                    Principal_Investigator_1_NPI STRING,
                    Principal_Investigator_1_First_Name STRING,
                    Principal_Investigator_1_Middle_Name STRING,
                    Principal_Investigator_1_Last_Name STRING,
                    Principal_Investigator_1_Name_Suffix STRING,
                    Principal_Investigator_1_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_1_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_1_City STRING,
                    Principal_Investigator_1_State STRING,
                    Principal_Investigator_1_Zip_Code STRING,
                    Principal_Investigator_1_Country STRING,
                    Principal_Investigator_1_Province STRING,
                    Principal_Investigator_1_Postal_Code STRING,
                    Principal_Investigator_1_Primary_Type_1 STRING,
                    Principal_Investigator_1_Primary_Type_2 STRING,
                    Principal_Investigator_1_Primary_Type_3 STRING,
                    Principal_Investigator_1_Primary_Type_4 STRING,
                    Principal_Investigator_1_Primary_Type_5 STRING,
                    Principal_Investigator_1_Primary_Type_6 STRING,
                    Principal_Investigator_1_Specialty_1 STRING,
                    Principal_Investigator_1_Specialty_2 STRING,
                    Principal_Investigator_1_Specialty_3 STRING,
                    Principal_Investigator_1_Specialty_4 STRING,
                    Principal_Investigator_1_Specialty_5 STRING,
                    Principal_Investigator_1_Specialty_6 STRING,
                    Principal_Investigator_1_License_State_code1 STRING,
                    Principal_Investigator_1_License_State_code2 STRING,
                    Principal_Investigator_1_License_State_code3 STRING,
                    Principal_Investigator_1_License_State_code4 STRING,
                    Principal_Investigator_1_License_State_code5 STRING,
                    Principal_Investigator_2_Covered_Recipient_Type STRING,
                    Principal_Investigator_2_Profile_ID STRING,
                    Principal_Investigator_2_NPI STRING,
                    Principal_Investigator_2_First_Name STRING,
                    Principal_Investigator_2_Middle_Name STRING,
                    Principal_Investigator_2_Last_Name STRING,
                    Principal_Investigator_2_Name_Suffix STRING,
                    Principal_Investigator_2_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_2_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_2_City STRING,
                    Principal_Investigator_2_State STRING,
                    Principal_Investigator_2_Zip_Code STRING,
                    Principal_Investigator_2_Country STRING,
                    Principal_Investigator_2_Province STRING,
                    Principal_Investigator_2_Postal_Code STRING,
                    Principal_Investigator_2_Primary_Type_1 STRING,
                    Principal_Investigator_2_Primary_Type_2 STRING,
                    Principal_Investigator_2_Primary_Type_3 STRING,
                    Principal_Investigator_2_Primary_Type_4 STRING,
                    Principal_Investigator_2_Primary_Type_5 STRING,
                    Principal_Investigator_2_Primary_Type_6 STRING,
                    Principal_Investigator_2_Specialty_1 STRING,
                    Principal_Investigator_2_Specialty_2 STRING,
                    Principal_Investigator_2_Specialty_3 STRING,
                    Principal_Investigator_2_Specialty_4 STRING,
                    Principal_Investigator_2_Specialty_5 STRING,
                    Principal_Investigator_2_Specialty_6 STRING,
                    Principal_Investigator_2_License_State_code1 STRING,
                    Principal_Investigator_2_License_State_code2 STRING,
                    Principal_Investigator_2_License_State_code3 STRING,
                    Principal_Investigator_2_License_State_code4 STRING,
                    Principal_Investigator_2_License_State_code5 STRING,
                    Principal_Investigator_3_Covered_Recipient_Type STRING,
                    Principal_Investigator_3_Profile_ID STRING,
                    Principal_Investigator_3_NPI STRING,
                    Principal_Investigator_3_First_Name STRING,
                    Principal_Investigator_3_Middle_Name STRING,
                    Principal_Investigator_3_Last_Name STRING,
                    Principal_Investigator_3_Name_Suffix STRING,
                    Principal_Investigator_3_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_3_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_3_City STRING,
                    Principal_Investigator_3_State STRING,
                    Principal_Investigator_3_Zip_Code STRING,
                    Principal_Investigator_3_Country STRING,
                    Principal_Investigator_3_Province STRING,
                    Principal_Investigator_3_Postal_Code STRING,
                    Principal_Investigator_3_Primary_Type_1 STRING,
                    Principal_Investigator_3_Primary_Type_2 STRING,
                    Principal_Investigator_3_Primary_Type_3 STRING,
                    Principal_Investigator_3_Primary_Type_4 STRING,
                    Principal_Investigator_3_Primary_Type_5 STRING,
                    Principal_Investigator_3_Primary_Type_6 STRING,
                    Principal_Investigator_3_Specialty_1 STRING,
                    Principal_Investigator_3_Specialty_2 STRING,
                    Principal_Investigator_3_Specialty_3 STRING,
                    Principal_Investigator_3_Specialty_4 STRING,
                    Principal_Investigator_3_Specialty_5 STRING,
                    Principal_Investigator_3_Specialty_6 STRING,
                    Principal_Investigator_3_License_State_code1 STRING,
                    Principal_Investigator_3_License_State_code2 STRING,
                    Principal_Investigator_3_License_State_code3 STRING,
                    Principal_Investigator_3_License_State_code4 STRING,
                    Principal_Investigator_3_License_State_code5 STRING,
                    Principal_Investigator_4_Covered_Recipient_Type STRING,
                    Principal_Investigator_4_Profile_ID STRING,
                    Principal_Investigator_4_NPI STRING,
                    Principal_Investigator_4_First_Name STRING,
                    Principal_Investigator_4_Middle_Name STRING,
                    Principal_Investigator_4_Last_Name STRING,
                    Principal_Investigator_4_Name_Suffix STRING,
                    Principal_Investigator_4_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_4_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_4_City STRING,
                    Principal_Investigator_4_State STRING,
                    Principal_Investigator_4_Zip_Code STRING,
                    Principal_Investigator_4_Country STRING,
                    Principal_Investigator_4_Province STRING,
                    Principal_Investigator_4_Postal_Code STRING,
                    Principal_Investigator_4_Primary_Type_1 STRING,
                    Principal_Investigator_4_Primary_Type_2 STRING,
                    Principal_Investigator_4_Primary_Type_3 STRING,
                    Principal_Investigator_4_Primary_Type_4 STRING,
                    Principal_Investigator_4_Primary_Type_5 STRING,
                    Principal_Investigator_4_Primary_Type_6 STRING,
                    Principal_Investigator_4_Specialty_1 STRING,
                    Principal_Investigator_4_Specialty_2 STRING,
                    Principal_Investigator_4_Specialty_3 STRING,
                    Principal_Investigator_4_Specialty_4 STRING,
                    Principal_Investigator_4_Specialty_5 STRING,
                    Principal_Investigator_4_Specialty_6 STRING,
                    Principal_Investigator_4_License_State_code1 STRING,
                    Principal_Investigator_4_License_State_code2 STRING,
                    Principal_Investigator_4_License_State_code3 STRING,
                    Principal_Investigator_4_License_State_code4 STRING,
                    Principal_Investigator_4_License_State_code5 STRING,
                    Principal_Investigator_5_Covered_Recipient_Type STRING,
                    Principal_Investigator_5_Profile_ID STRING,
                    Principal_Investigator_5_NPI STRING,
                    Principal_Investigator_5_First_Name STRING,
                    Principal_Investigator_5_Middle_Name STRING,
                    Principal_Investigator_5_Last_Name STRING,
                    Principal_Investigator_5_Name_Suffix STRING,
                    Principal_Investigator_5_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_5_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_5_City STRING,
                    Principal_Investigator_5_State STRING,
                    Principal_Investigator_5_Zip_Code STRING,
                    Principal_Investigator_5_Country STRING,
                    Principal_Investigator_5_Province STRING,
                    Principal_Investigator_5_Postal_Code STRING,
                    Principal_Investigator_5_Primary_Type_1 STRING,
                    Principal_Investigator_5_Primary_Type_2 STRING,
                    Principal_Investigator_5_Primary_Type_3 STRING,
                    Principal_Investigator_5_Primary_Type_4 STRING,
                    Principal_Investigator_5_Primary_Type_5 STRING,
                    Principal_Investigator_5_Primary_Type_6 STRING,
                    Principal_Investigator_5_Specialty_1 STRING,
                    Principal_Investigator_5_Specialty_2 STRING,
                    Principal_Investigator_5_Specialty_3 STRING,
                    Principal_Investigator_5_Specialty_4 STRING,
                    Principal_Investigator_5_Specialty_5 STRING,
                    Principal_Investigator_5_Specialty_6 STRING,
                    Principal_Investigator_5_License_State_code1 STRING,
                    Principal_Investigator_5_License_State_code2 STRING,
                    Principal_Investigator_5_License_State_code3 STRING,
                    Principal_Investigator_5_License_State_code4 STRING,
                    Principal_Investigator_5_License_State_code5 STRING,
                    Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name STRING,
                    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID INT64,
                    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name STRING,
                    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State STRING,
                    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country STRING,
                    Related_Product_Indicator STRING,
                    Covered_or_Noncovered_Indicator_1 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1 STRING,
                    Product_Category_or_Therapeutic_Area_1 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1 STRING,
                    Associated_Drug_or_Biological_NDC_1 STRING,
                    Associated_Device_or_Medical_Supply_PDI_1 STRING,
                    Covered_or_Noncovered_Indicator_2 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2 STRING,
                    Product_Category_or_Therapeutic_Area_2 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2 STRING,
                    Associated_Drug_or_Biological_NDC_2 STRING,
                    Associated_Device_or_Medical_Supply_PDI_2 STRING,
                    Covered_or_Noncovered_Indicator_3 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3 STRING,
                    Product_Category_or_Therapeutic_Area_3 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3 STRING,
                    Associated_Drug_or_Biological_NDC_3 STRING,
                    Associated_Device_or_Medical_Supply_PDI_3 STRING,
                    Covered_or_Noncovered_Indicator_4 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4 STRING,
                    Product_Category_or_Therapeutic_Area_4 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4 STRING,
                    Associated_Drug_or_Biological_NDC_4 STRING,
                    Associated_Device_or_Medical_Supply_PDI_4 STRING,
                    Covered_or_Noncovered_Indicator_5 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5 STRING,
                    Product_Category_or_Therapeutic_Area_5 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5 STRING,
                    Associated_Drug_or_Biological_NDC_5 STRING,
                    Associated_Device_or_Medical_Supply_PDI_5 STRING,
                    Total_Amount_of_Payment_USDollars FLOAT64,
                    Date_of_Payment STRING,
                    Form_of_Payment_or_Transfer_of_Value STRING,
                    Expenditure_Category1 STRING,
                    Expenditure_Category2 STRING,
                    Expenditure_Category3 STRING,
                    Expenditure_Category4 STRING,
                    Expenditure_Category5 STRING,
                    Expenditure_Category6 STRING,
                    Preclinical_Research_Indicator STRING,
                    Delay_in_Publication_Indicator STRING,
                    Name_of_Study STRING,
                    Dispute_Status_for_Publication STRING,
                    Record_ID INT64,
                    Program_Year INT64,
                    Payment_Publication_Date STRING,
                    ClinicalTrials_Gov_Identifier STRING,
                    Research_Information_Link STRING,
                    Context_of_Research STRING
                    )
                """,
                "useLegacySql": False,
            }
        },
        retries=3,
    )

    create_external_table_task = BigQueryInsertJobOperator(
        task_id="create_external_table",
        gcp_conn_id="gcp-airflow",
        configuration={
            "query": {
                "query": f"""
                    CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{BIGQUERY_DATASET}.{table_name_template}_ext` (
                    Change_Type STRING,
                    Covered_Recipient_Type STRING,
                    Noncovered_Recipient_Entity_Name STRING,
                    Teaching_Hospital_CCN STRING,
                    Teaching_Hospital_ID STRING,
                    Teaching_Hospital_Name STRING,
                    Covered_Recipient_Profile_ID STRING,
                    Covered_Recipient_NPI STRING,
                    Covered_Recipient_First_Name STRING,
                    Covered_Recipient_Middle_Name STRING,
                    Covered_Recipient_Last_Name STRING,
                    Covered_Recipient_Name_Suffix STRING,
                    Recipient_Primary_Business_Street_Address_Line1 STRING,
                    Recipient_Primary_Business_Street_Address_Line2 STRING,
                    Recipient_City STRING,
                    Recipient_State STRING,
                    Recipient_Zip_Code STRING,
                    Recipient_Country STRING,
                    Recipient_Province STRING,
                    Recipient_Postal_Code STRING,
                    Covered_Recipient_Primary_Type_1 STRING,
                    Covered_Recipient_Primary_Type_2 STRING,
                    Covered_Recipient_Primary_Type_3 STRING,
                    Covered_Recipient_Primary_Type_4 STRING,
                    Covered_Recipient_Primary_Type_5 STRING,
                    Covered_Recipient_Primary_Type_6 STRING,
                    Covered_Recipient_Specialty_1 STRING,
                    Covered_Recipient_Specialty_2 STRING,
                    Covered_Recipient_Specialty_3 STRING,
                    Covered_Recipient_Specialty_4 STRING,
                    Covered_Recipient_Specialty_5 STRING,
                    Covered_Recipient_Specialty_6 STRING,
                    Covered_Recipient_License_State_code1 STRING,
                    Covered_Recipient_License_State_code2 STRING,
                    Covered_Recipient_License_State_code3 STRING,
                    Covered_Recipient_License_State_code4 STRING,
                    Covered_Recipient_License_State_code5 STRING,
                    Principal_Investigator_1_Covered_Recipient_Type STRING,
                    Principal_Investigator_1_Profile_ID STRING,
                    Principal_Investigator_1_NPI STRING,
                    Principal_Investigator_1_First_Name STRING,
                    Principal_Investigator_1_Middle_Name STRING,
                    Principal_Investigator_1_Last_Name STRING,
                    Principal_Investigator_1_Name_Suffix STRING,
                    Principal_Investigator_1_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_1_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_1_City STRING,
                    Principal_Investigator_1_State STRING,
                    Principal_Investigator_1_Zip_Code STRING,
                    Principal_Investigator_1_Country STRING,
                    Principal_Investigator_1_Province STRING,
                    Principal_Investigator_1_Postal_Code STRING,
                    Principal_Investigator_1_Primary_Type_1 STRING,
                    Principal_Investigator_1_Primary_Type_2 STRING,
                    Principal_Investigator_1_Primary_Type_3 STRING,
                    Principal_Investigator_1_Primary_Type_4 STRING,
                    Principal_Investigator_1_Primary_Type_5 STRING,
                    Principal_Investigator_1_Primary_Type_6 STRING,
                    Principal_Investigator_1_Specialty_1 STRING,
                    Principal_Investigator_1_Specialty_2 STRING,
                    Principal_Investigator_1_Specialty_3 STRING,
                    Principal_Investigator_1_Specialty_4 STRING,
                    Principal_Investigator_1_Specialty_5 STRING,
                    Principal_Investigator_1_Specialty_6 STRING,
                    Principal_Investigator_1_License_State_code1 STRING,
                    Principal_Investigator_1_License_State_code2 STRING,
                    Principal_Investigator_1_License_State_code3 STRING,
                    Principal_Investigator_1_License_State_code4 STRING,
                    Principal_Investigator_1_License_State_code5 STRING,
                    Principal_Investigator_2_Covered_Recipient_Type STRING,
                    Principal_Investigator_2_Profile_ID STRING,
                    Principal_Investigator_2_NPI STRING,
                    Principal_Investigator_2_First_Name STRING,
                    Principal_Investigator_2_Middle_Name STRING,
                    Principal_Investigator_2_Last_Name STRING,
                    Principal_Investigator_2_Name_Suffix STRING,
                    Principal_Investigator_2_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_2_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_2_City STRING,
                    Principal_Investigator_2_State STRING,
                    Principal_Investigator_2_Zip_Code STRING,
                    Principal_Investigator_2_Country STRING,
                    Principal_Investigator_2_Province STRING,
                    Principal_Investigator_2_Postal_Code STRING,
                    Principal_Investigator_2_Primary_Type_1 STRING,
                    Principal_Investigator_2_Primary_Type_2 STRING,
                    Principal_Investigator_2_Primary_Type_3 STRING,
                    Principal_Investigator_2_Primary_Type_4 STRING,
                    Principal_Investigator_2_Primary_Type_5 STRING,
                    Principal_Investigator_2_Primary_Type_6 STRING,
                    Principal_Investigator_2_Specialty_1 STRING,
                    Principal_Investigator_2_Specialty_2 STRING,
                    Principal_Investigator_2_Specialty_3 STRING,
                    Principal_Investigator_2_Specialty_4 STRING,
                    Principal_Investigator_2_Specialty_5 STRING,
                    Principal_Investigator_2_Specialty_6 STRING,
                    Principal_Investigator_2_License_State_code1 STRING,
                    Principal_Investigator_2_License_State_code2 STRING,
                    Principal_Investigator_2_License_State_code3 STRING,
                    Principal_Investigator_2_License_State_code4 STRING,
                    Principal_Investigator_2_License_State_code5 STRING,
                    Principal_Investigator_3_Covered_Recipient_Type STRING,
                    Principal_Investigator_3_Profile_ID STRING,
                    Principal_Investigator_3_NPI STRING,
                    Principal_Investigator_3_First_Name STRING,
                    Principal_Investigator_3_Middle_Name STRING,
                    Principal_Investigator_3_Last_Name STRING,
                    Principal_Investigator_3_Name_Suffix STRING,
                    Principal_Investigator_3_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_3_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_3_City STRING,
                    Principal_Investigator_3_State STRING,
                    Principal_Investigator_3_Zip_Code STRING,
                    Principal_Investigator_3_Country STRING,
                    Principal_Investigator_3_Province STRING,
                    Principal_Investigator_3_Postal_Code STRING,
                    Principal_Investigator_3_Primary_Type_1 STRING,
                    Principal_Investigator_3_Primary_Type_2 STRING,
                    Principal_Investigator_3_Primary_Type_3 STRING,
                    Principal_Investigator_3_Primary_Type_4 STRING,
                    Principal_Investigator_3_Primary_Type_5 STRING,
                    Principal_Investigator_3_Primary_Type_6 STRING,
                    Principal_Investigator_3_Specialty_1 STRING,
                    Principal_Investigator_3_Specialty_2 STRING,
                    Principal_Investigator_3_Specialty_3 STRING,
                    Principal_Investigator_3_Specialty_4 STRING,
                    Principal_Investigator_3_Specialty_5 STRING,
                    Principal_Investigator_3_Specialty_6 STRING,
                    Principal_Investigator_3_License_State_code1 STRING,
                    Principal_Investigator_3_License_State_code2 STRING,
                    Principal_Investigator_3_License_State_code3 STRING,
                    Principal_Investigator_3_License_State_code4 STRING,
                    Principal_Investigator_3_License_State_code5 STRING,
                    Principal_Investigator_4_Covered_Recipient_Type STRING,
                    Principal_Investigator_4_Profile_ID STRING,
                    Principal_Investigator_4_NPI STRING,
                    Principal_Investigator_4_First_Name STRING,
                    Principal_Investigator_4_Middle_Name STRING,
                    Principal_Investigator_4_Last_Name STRING,
                    Principal_Investigator_4_Name_Suffix STRING,
                    Principal_Investigator_4_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_4_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_4_City STRING,
                    Principal_Investigator_4_State STRING,
                    Principal_Investigator_4_Zip_Code STRING,
                    Principal_Investigator_4_Country STRING,
                    Principal_Investigator_4_Province STRING,
                    Principal_Investigator_4_Postal_Code STRING,
                    Principal_Investigator_4_Primary_Type_1 STRING,
                    Principal_Investigator_4_Primary_Type_2 STRING,
                    Principal_Investigator_4_Primary_Type_3 STRING,
                    Principal_Investigator_4_Primary_Type_4 STRING,
                    Principal_Investigator_4_Primary_Type_5 STRING,
                    Principal_Investigator_4_Primary_Type_6 STRING,
                    Principal_Investigator_4_Specialty_1 STRING,
                    Principal_Investigator_4_Specialty_2 STRING,
                    Principal_Investigator_4_Specialty_3 STRING,
                    Principal_Investigator_4_Specialty_4 STRING,
                    Principal_Investigator_4_Specialty_5 STRING,
                    Principal_Investigator_4_Specialty_6 STRING,
                    Principal_Investigator_4_License_State_code1 STRING,
                    Principal_Investigator_4_License_State_code2 STRING,
                    Principal_Investigator_4_License_State_code3 STRING,
                    Principal_Investigator_4_License_State_code4 STRING,
                    Principal_Investigator_4_License_State_code5 STRING,
                    Principal_Investigator_5_Covered_Recipient_Type STRING,
                    Principal_Investigator_5_Profile_ID STRING,
                    Principal_Investigator_5_NPI STRING,
                    Principal_Investigator_5_First_Name STRING,
                    Principal_Investigator_5_Middle_Name STRING,
                    Principal_Investigator_5_Last_Name STRING,
                    Principal_Investigator_5_Name_Suffix STRING,
                    Principal_Investigator_5_Business_Street_Address_Line1 STRING,
                    Principal_Investigator_5_Business_Street_Address_Line2 STRING,
                    Principal_Investigator_5_City STRING,
                    Principal_Investigator_5_State STRING,
                    Principal_Investigator_5_Zip_Code STRING,
                    Principal_Investigator_5_Country STRING,
                    Principal_Investigator_5_Province STRING,
                    Principal_Investigator_5_Postal_Code STRING,
                    Principal_Investigator_5_Primary_Type_1 STRING,
                    Principal_Investigator_5_Primary_Type_2 STRING,
                    Principal_Investigator_5_Primary_Type_3 STRING,
                    Principal_Investigator_5_Primary_Type_4 STRING,
                    Principal_Investigator_5_Primary_Type_5 STRING,
                    Principal_Investigator_5_Primary_Type_6 STRING,
                    Principal_Investigator_5_Specialty_1 STRING,
                    Principal_Investigator_5_Specialty_2 STRING,
                    Principal_Investigator_5_Specialty_3 STRING,
                    Principal_Investigator_5_Specialty_4 STRING,
                    Principal_Investigator_5_Specialty_5 STRING,
                    Principal_Investigator_5_Specialty_6 STRING,
                    Principal_Investigator_5_License_State_code1 STRING,
                    Principal_Investigator_5_License_State_code2 STRING,
                    Principal_Investigator_5_License_State_code3 STRING,
                    Principal_Investigator_5_License_State_code4 STRING,
                    Principal_Investigator_5_License_State_code5 STRING,
                    Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name STRING,
                    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID INT64,
                    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name STRING,
                    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State STRING,
                    Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country STRING,
                    Related_Product_Indicator STRING,
                    Covered_or_Noncovered_Indicator_1 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1 STRING,
                    Product_Category_or_Therapeutic_Area_1 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1 STRING,
                    Associated_Drug_or_Biological_NDC_1 STRING,
                    Associated_Device_or_Medical_Supply_PDI_1 STRING,
                    Covered_or_Noncovered_Indicator_2 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2 STRING,
                    Product_Category_or_Therapeutic_Area_2 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2 STRING,
                    Associated_Drug_or_Biological_NDC_2 STRING,
                    Associated_Device_or_Medical_Supply_PDI_2 STRING,
                    Covered_or_Noncovered_Indicator_3 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3 STRING,
                    Product_Category_or_Therapeutic_Area_3 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3 STRING,
                    Associated_Drug_or_Biological_NDC_3 STRING,
                    Associated_Device_or_Medical_Supply_PDI_3 STRING,
                    Covered_or_Noncovered_Indicator_4 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4 STRING,
                    Product_Category_or_Therapeutic_Area_4 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4 STRING,
                    Associated_Drug_or_Biological_NDC_4 STRING,
                    Associated_Device_or_Medical_Supply_PDI_4 STRING,
                    Covered_or_Noncovered_Indicator_5 STRING,
                    Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5 STRING,
                    Product_Category_or_Therapeutic_Area_5 STRING,
                    Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5 STRING,
                    Associated_Drug_or_Biological_NDC_5 STRING,
                    Associated_Device_or_Medical_Supply_PDI_5 STRING,
                    Total_Amount_of_Payment_USDollars FLOAT64,
                    Date_of_Payment STRING,
                    Form_of_Payment_or_Transfer_of_Value STRING,
                    Expenditure_Category1 STRING,
                    Expenditure_Category2 STRING,
                    Expenditure_Category3 STRING,
                    Expenditure_Category4 STRING,
                    Expenditure_Category5 STRING,
                    Expenditure_Category6 STRING,
                    Preclinical_Research_Indicator STRING,
                    Delay_in_Publication_Indicator STRING,
                    Name_of_Study STRING,
                    Dispute_Status_for_Publication STRING,
                    Record_ID INT64,
                    Program_Year INT64,
                    Payment_Publication_Date STRING,
                    ClinicalTrials_Gov_Identifier STRING,
                    Research_Information_Link STRING,
                    Context_of_Research STRING
                    )
                    OPTIONS (
                        uris = ['gs://{BUCKET}/raw/{parquet_filename_template}'],
                        format = 'PARQUET'
                    );
                """,
                "useLegacySql": False,
            }
        },
        retries=3,
    )

    create_temp_table_task = BigQueryInsertJobOperator(
        task_id="create_temp_table",
        gcp_conn_id="gcp-airflow",
        configuration={
            "query": {
                "query": f"""
                    CREATE OR REPLACE TABLE `{PROJECT_ID}.{BIGQUERY_DATASET}.{table_name_template}_tmp` AS
                    SELECT
                        "{parquet_filename_template}" AS filename,
                         *
                    FROM `{PROJECT_ID}.{BIGQUERY_DATASET}.{table_name_template}_ext`;
                """,
                "useLegacySql": False,
            }
        },
        retries=3,
    )

    merge_to_final_table_task = BigQueryInsertJobOperator(
        task_id="merge_to_final_table",
        gcp_conn_id="gcp-airflow",
        configuration={
            "query": {
                "query": f"""
                    INSERT INTO `{PROJECT_ID}.{BIGQUERY_DATASET}.{final_name_template}` 
                    SELECT *
                    FROM `{PROJECT_ID}.{BIGQUERY_DATASET}.{table_name_template}_tmp`;
                """,
                "useLegacySql": False,
            }
        },
        retries=3,
    )

    cleanup_task = BashOperator(
        task_id="cleanup_files",
        bash_command=f"rm -rf {EXTRACT_PATH}",
    )

    # Define overall task sequence
    download_task >> list_task >> rsrch_to_parquet_task >> upload_to_gcs >> create_final_table_task >> create_external_table_task >> create_temp_table_task >> merge_to_final_table_task >> cleanup_task
